//! # ExprVisitor 核心展开逻辑
//!
//! 为 `#[derive(ExprVisitor)]` 提供 AST 节点的默认遍历代码生成。
//!
//! ## 设计目标
//!
//! 消除 `nuzo_frontend::ast::default_visit_expr` 中 40+ 行手写递归遍历代码。
//! derive 自动分析 `Expr` 枚举的每个变体的字段类型，生成等价的递归遍历，
//! 用户只需在 `Expr` 上加 `#[derive(ExprVisitor)]`，即可获得一个
//! `visit_children_derived` 内建方法，行为与手写 `default_visit_expr` 一致。
//!
//! ## 生成的代码
//!
//! ```ignore
//! #[derive(ExprVisitor)]
//! pub enum Expr { ... }
//!
//! // 生成：
//! impl Expr {
//!     pub fn visit_children_derived<V: ExprVisitor + ?Sized>(&self, visitor: &mut V) {
//!         match self {
//!             Expr::Number { .. } | Expr::String { .. } | Expr::Bool { .. } | Expr::Nil { .. } => {
//!                 visitor.visit_literal(self);
//!             }
//!             Expr::Ident { name, span } => {
//!                 visitor.visit_ident(name, span);
//!             }
//!             // ... 其余变体按字段类型自动递归
//!         }
//!     }
//! }
//! ```
//!
//! ## MVP 支持范围
//!
//! - **字面量变体**（按名称识别 `Number`/`String`/`Bool`/`Nil`）→ `visit_literal`
//! - **Ident 变体**（按名称识别）→ `visit_ident`
//! - **Fn/Closure 变体**（按名称识别）→ `visit_fn`
//! - **Dict 变体**（按名称识别）→ 遍历 `Vec<(String, Expr)>` 的 value
//! - **Match 变体**（按名称识别）→ 遍历 scrutinee 和 arms 中的 pattern/body
//! - **其余变体**：根据字段类型自动生成递归调用
//!   - `Box<Expr>` → `visitor.visit_expr(field)`
//!   - `Vec<Expr>` → `for el in field { visitor.visit_expr(el); }`
//!   - `Option<Box<Expr>>` → `if let Some(v) = field { visitor.visit_expr(v); }`
//!   - `Block`（= `Vec<Stmt>`）→ `visitor.visit_block(field)`
//!   - `Option<Block>` → `if let Some(b) = field { visitor.visit_block(b); }`
//!   - 其他类型（Span/BinaryOp/bool/String/...）→ 跳过
//!
//! ## 不支持的特性
//!
//! - 不支持自定义遍历策略（如「跳过某个字段」属性）—— 可后续扩展
//! - 不支持结构体（仅 enum）—— AST 节点都是 enum
//! - 不支持泛型 Expr（当前 Expr 无泛型参数）

use crate::diag::SpannedError;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Fields, GenericArgument, PathArguments, Type};

// ══════════════════════════════════════════════════════════════════
// 核心展开
// ══════════════════════════════════════════════════════════════════

pub fn expand_expr_visitor(input: &DeriveInput) -> syn::Result<TokenStream> {
    let enum_name = &input.ident;
    let data_enum = match &input.data {
        Data::Enum(e) => e,
        _ => {
            return Err(SpannedError::new_spanned(
                enum_name,
                "ExprVisitor can only be derived for enums",
            )
            .into_inner());
        }
    };

    let match_arms: Vec<TokenStream> = data_enum.variants.iter().map(generate_match_arm).collect();

    // 生成的方法名：visit_children_derived
    // 与手写 default_visit_expr 区分，便于行为对比测试
    let method_name = format_ident!("visit_children_derived");

    Ok(quote! {
        impl #enum_name {
            /// Auto-generated by `#[derive(ExprVisitor)]`.
            ///
            /// 默认的子节点遍历实现，行为等价于 `default_visit_expr`。
            ///
            /// # 用途
            ///
            /// - 作为 `ExprVisitor::visit_expr` 默认实现的备选
            /// - 通过对比测试验证 derive 生成代码与手写版本行为一致
            ///
            /// # 与 `default_visit_expr` 的区别
            ///
            /// - `default_visit_expr` 是自由函数：`fn(visitor, expr)`
            /// - `visit_children_derived` 是内建方法：`expr.visit_children_derived(visitor)`
            /// - 行为完全等价
            //
            // `#[allow(unused_variables)]`：match 模式需绑定所有字段以满足穷尽性，
            // 但宏只对 Box<Expr> / Vec<Expr> / Block 等类型生成递归调用，
            // 其余字段（如 span / op / name / var_name / inclusive）被绑定后未读。
            // 这是宏生成代码的固有特性，不污染用户代码。
            #[allow(unused_variables)]
            pub fn #method_name<V: ExprVisitor + ?Sized>(&self, visitor: &mut V) {
                match self {
                    #(#match_arms)*
                }
            }
        }
    })
}

// ══════════════════════════════════════════════════════════════════
// 变体分类与 match arm 生成
// ══════════════════════════════════════════════════════════════════

fn generate_match_arm(variant: &syn::Variant) -> TokenStream {
    let variant_ident = &variant.ident;
    let variant_name = variant.ident.to_string();

    // 按变体名称做特殊处理（MVP 策略：基于 AST 的稳定命名约定）
    match variant_name.as_str() {
        // 字面量变体 → visit_literal
        "Number" | "String" | "Bool" | "Nil" => {
            return generate_literal_arm(variant_ident, &variant.fields);
        }
        // Ident 变体 → visit_ident
        "Ident" => {
            return generate_ident_arm(variant_ident, &variant.fields);
        }
        // Fn 变体 → visit_fn (with name)
        "Fn" => {
            return generate_fn_arm(variant_ident, &variant.fields, /* with_name = */ true);
        }
        // Closure 变体 → visit_fn (None for name)
        "Closure" => {
            return generate_fn_arm(variant_ident, &variant.fields, /* with_name = */ false);
        }
        // Dict 变体 → 遍历 Vec<(String, Expr)>
        "Dict" => {
            return generate_dict_arm(variant_ident, &variant.fields);
        }
        // Match 变体 → 遍历 scrutinee + arms
        "Match" => {
            return generate_match_pattern_arm(variant_ident, &variant.fields);
        }
        // Block 变体 → 字段类型是 Vec<Stmt>（非 Block 别名），需按名称特化
        "Block" => {
            return generate_block_arm(variant_ident, &variant.fields);
        }
        // Try 变体 → 手写实现只访问 body，显式忽略 keep_block/catch_clause
        "Try" => {
            return generate_try_arm(variant_ident, &variant.fields);
        }
        _ => {}
    }

    // 通用情况：根据字段类型自动生成递归调用
    generate_generic_arm(variant_ident, &variant.fields)
}

// ── 字面量变体（Number/String/Bool/Nil）──────────────────────────

fn generate_literal_arm(variant_ident: &syn::Ident, fields: &Fields) -> TokenStream {
    let pattern = match fields {
        Fields::Unit => quote! { Self::#variant_ident },
        Fields::Unnamed(_) => quote! { Self::#variant_ident(..) },
        Fields::Named(_) => quote! { Self::#variant_ident { .. } },
    };
    quote! {
        #pattern => {
            visitor.visit_literal(self);
        }
    }
}

// ── Ident 变体 ─────────────────────────────────────────────────

fn generate_ident_arm(variant_ident: &syn::Ident, fields: &Fields) -> TokenStream {
    if let Fields::Named(fields) = fields {
        let name_field = fields.named.iter().find_map(|f| {
            (f.ident.as_ref().map(|i| i == "name").unwrap_or(false))
                .then(|| f.ident.as_ref().unwrap())
        });
        let span_field = fields.named.iter().find_map(|f| {
            (f.ident.as_ref().map(|i| i == "span").unwrap_or(false))
                .then(|| f.ident.as_ref().unwrap())
        });
        if let (Some(name), Some(span)) = (name_field, span_field) {
            return quote! {
                Self::#variant_ident { name: #name, span: #span, .. } => {
                    visitor.visit_ident(#name, #span);
                }
            };
        }
    }
    // 兜底：结构不匹配时不递归（保持穷尽性）
    quote! { Self::#variant_ident { .. } => {} }
}

// ── Fn/Closure 变体 ────────────────────────────────────────────

fn generate_fn_arm(variant_ident: &syn::Ident, fields: &Fields, with_name: bool) -> TokenStream {
    if let Fields::Named(fields) = fields {
        // 查找各字段标识符（用 filter 替代冗长的 find_map + then 组合）
        let find_field = |name: &str| -> Option<&syn::Ident> {
            fields.named.iter().find_map(|f| f.ident.as_ref().filter(|i| *i == name))
        };

        let params_field = find_field("params");
        let body_field = find_field("body");
        let span_field = find_field("span");

        if with_name {
            // Fn 变体：模式必须绑定 `name`，函数体才能引用 name.as_deref()
            let name_field = find_field("name").expect("Fn variant must have a `name` field");
            if let (Some(params), Some(body), Some(span)) = (params_field, body_field, span_field) {
                return quote! {
                    Self::#variant_ident {
                        name: #name_field, params: #params, body: #body, span: #span, ..
                    } => {
                        // name.as_deref() 把 Option<String> 转为 Option<&str>
                        visitor.visit_fn(#name_field.as_deref(), #params, #body, #span);
                    }
                };
            }
        } else {
            // Closure 变体：无 name 字段，传 None
            if let (Some(params), Some(body), Some(span)) = (params_field, body_field, span_field) {
                return quote! {
                    Self::#variant_ident { params: #params, body: #body, span: #span, .. } => {
                        visitor.visit_fn(None, #params, #body, #span);
                    }
                };
            }
        }
    }
    quote! { Self::#variant_ident { .. } => {} }
}

// ── Dict 变体 ──────────────────────────────────────────────────

fn generate_dict_arm(variant_ident: &syn::Ident, fields: &Fields) -> TokenStream {
    if let Fields::Named(fields) = fields {
        let pairs_field = fields.named.iter().find_map(|f| {
            (f.ident.as_ref().map(|i| i == "pairs").unwrap_or(false))
                .then(|| f.ident.as_ref().unwrap())
        });
        if let Some(pairs) = pairs_field {
            return quote! {
                Self::#variant_ident { pairs: #pairs, .. } => {
                    for (_, val) in #pairs {
                        visitor.visit_expr(val);
                    }
                }
            };
        }
    }
    quote! { Self::#variant_ident { .. } => {} }
}

// ── Match 变体 ─────────────────────────────────────────────────

fn generate_match_pattern_arm(variant_ident: &syn::Ident, fields: &Fields) -> TokenStream {
    if let Fields::Named(fields) = fields {
        let scrutinee_field = fields.named.iter().find_map(|f| {
            (f.ident.as_ref().map(|i| i == "scrutinee").unwrap_or(false))
                .then(|| f.ident.as_ref().unwrap())
        });
        let arms_field = fields.named.iter().find_map(|f| {
            (f.ident.as_ref().map(|i| i == "arms").unwrap_or(false))
                .then(|| f.ident.as_ref().unwrap())
        });
        if let (Some(scrutinee), Some(arms)) = (scrutinee_field, arms_field) {
            return quote! {
                Self::#variant_ident { scrutinee: #scrutinee, arms: #arms, .. } => {
                    visitor.visit_expr(#scrutinee);
                    for arm in #arms {
                        match &arm.pattern {
                            MatchPattern::Literal(lit) => visitor.visit_expr(lit),
                            MatchPattern::Range { start, end, .. } => {
                                visitor.visit_expr(start);
                                visitor.visit_expr(end);
                            }
                            MatchPattern::Variable(_) | MatchPattern::Wildcard => {}
                        }
                        visitor.visit_expr(&arm.body);
                    }
                }
            };
        }
    }
    quote! { Self::#variant_ident { .. } => {} }
}

// ── Block 变体 ────────────────────────────────────────────────
// 特化原因：statements 字段类型是 Vec<Stmt>，无法通过类型名 Block 识别

fn generate_block_arm(variant_ident: &syn::Ident, fields: &Fields) -> TokenStream {
    if let Fields::Named(fields) = fields {
        let statements_field =
            fields.named.iter().find_map(|f| f.ident.as_ref().filter(|i| *i == "statements"));
        if let Some(statements) = statements_field {
            return quote! {
                Self::#variant_ident { statements: #statements, .. } => {
                    visitor.visit_block(#statements);
                }
            };
        }
    }
    quote! { Self::#variant_ident { .. } => {} }
}

// ── Try 变体 ──────────────────────────────────────────────────
// 特化原因：手写 default_visit_expr 只访问 body，显式忽略 keep_block/catch_clause
// 若用通用规则会同时访问 keep_block: Option<Block>，与手写行为不一致

fn generate_try_arm(variant_ident: &syn::Ident, fields: &Fields) -> TokenStream {
    if let Fields::Named(fields) = fields {
        let body_field =
            fields.named.iter().find_map(|f| f.ident.as_ref().filter(|i| *i == "body"));
        if let Some(body) = body_field {
            return quote! {
                Self::#variant_ident { body: #body, .. } => {
                    visitor.visit_block(#body);
                }
            };
        }
    }
    quote! { Self::#variant_ident { .. } => {} }
}

// ── 通用变体：按字段类型自动递归 ───────────────────────────────

fn generate_generic_arm(variant_ident: &syn::Ident, fields: &Fields) -> TokenStream {
    match fields {
        Fields::Unit => {
            quote! {
                Self::#variant_ident => {}
            }
        }
        Fields::Unnamed(fields) => {
            let field_count = fields.unnamed.len();
            let field_idents: Vec<syn::Ident> =
                (0..field_count).map(|i| format_ident!("field{}", i)).collect();
            let body: Vec<TokenStream> = fields
                .unnamed
                .iter()
                .zip(field_idents.iter())
                .filter_map(|(f, ident)| generate_field_recursion(&f.ty, ident))
                .collect();
            quote! {
                Self::#variant_ident(#(#field_idents),*) => {
                    #(#body)*
                }
            }
        }
        Fields::Named(fields) => {
            // 提取所有字段名 + 递归调用
            let field_idents: Vec<&syn::Ident> =
                fields.named.iter().map(|f| f.ident.as_ref().unwrap()).collect();
            let body: Vec<TokenStream> = fields
                .named
                .iter()
                .filter_map(|f| {
                    let ident = f.ident.as_ref().unwrap();
                    generate_field_recursion(&f.ty, ident)
                })
                .collect();
            quote! {
                Self::#variant_ident { #(#field_idents),* } => {
                    #(#body)*
                }
            }
        }
    }
}

// ══════════════════════════════════════════════════════════════════
// 字段类型识别与递归调用生成
// ══════════════════════════════════════════════════════════════════

/// 根据字段类型生成对应的递归调用，无法识别的类型返回 `None`（跳过）。
fn generate_field_recursion(ty: &Type, ident: &syn::Ident) -> Option<TokenStream> {
    // Box<Expr> → visitor.visit_expr(ident)
    if is_box_expr(ty) {
        return Some(quote! { visitor.visit_expr(#ident); });
    }
    // Vec<Expr> → for el in ident { visitor.visit_expr(el); }
    if is_vec_expr(ty) {
        return Some(quote! { for el in #ident { visitor.visit_expr(el); } });
    }
    // Option<Box<Expr>> → if let Some(v) = ident { visitor.visit_expr(v); }
    if is_option_box_expr(ty) {
        return Some(quote! { if let Some(v) = #ident { visitor.visit_expr(v); } });
    }
    // Block (type alias for Vec<Stmt>) → visitor.visit_block(ident)
    if is_block(ty) {
        return Some(quote! { visitor.visit_block(#ident); });
    }
    // Option<Block> → if let Some(b) = ident { visitor.visit_block(b); }
    if is_option_block(ty) {
        return Some(quote! { if let Some(b) = #ident { visitor.visit_block(b); } });
    }
    None
}

// ── 类型识别辅助函数 ───────────────────────────────────────────

/// 判断类型是否为 `Expr`（单段路径，无泛型参数）
fn is_expr(ty: &Type) -> bool {
    if let Type::Path(p) = ty {
        p.path.segments.len() == 1
            && p.path.segments[0].ident == "Expr"
            && p.path.segments[0].arguments.is_empty()
    } else {
        false
    }
}

/// 判断类型是否为 `Box<Expr>`
fn is_box_expr(ty: &Type) -> bool {
    is_generic_single(ty, "Box", is_expr)
}

/// 判断类型是否为 `Vec<Expr>`
fn is_vec_expr(ty: &Type) -> bool {
    is_generic_single(ty, "Vec", is_expr)
}

/// 判断类型是否为 `Option<Box<Expr>>`
fn is_option_box_expr(ty: &Type) -> bool {
    if let Some(inner) = get_generic_arg(ty, "Option") {
        return is_box_expr(inner);
    }
    false
}

/// 判断类型是否为 `Block`（Vec<Stmt> 的类型别名）
fn is_block(ty: &Type) -> bool {
    if let Type::Path(p) = ty {
        p.path.segments.len() == 1 && p.path.segments[0].ident == "Block"
    } else {
        false
    }
}

/// 判断类型是否为 `Option<Block>`
fn is_option_block(ty: &Type) -> bool {
    if let Some(inner) = get_generic_arg(ty, "Option") {
        return is_block(inner);
    }
    false
}

/// 通用：判断类型是否为 `Outer<Inner>`，并用 `inner_check` 校验 Inner
fn is_generic_single(ty: &Type, outer: &str, inner_check: impl Fn(&Type) -> bool) -> bool {
    if let Some(inner) = get_generic_arg(ty, outer) {
        return inner_check(inner);
    }
    false
}

/// 提取 `Outer<T>` 中的 `T`，否则返回 None
fn get_generic_arg<'a>(ty: &'a Type, outer: &str) -> Option<&'a Type> {
    if let Type::Path(p) = ty
        && p.path.segments.len() == 1
        && p.path.segments[0].ident == outer
        && let PathArguments::AngleBracketed(args) = &p.path.segments[0].arguments
        && args.args.len() == 1
        && let GenericArgument::Type(inner) = &args.args[0]
    {
        return Some(inner);
    }
    None
}

// ══════════════════════════════════════════════════════════════════
// Tests
// ══════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use syn::parse_quote;

    // ── 基础：字面量变体 ──────────────────────────────────────

    #[test]
    fn literal_variants_generate_visit_literal() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Number { value: f64, span: Span },
                String { value: String, span: Span },
                Bool { value: bool, span: Span },
                Nil { span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(code.contains("visit_literal (self)"), "Number → visit_literal");
        // 所有字面量变体共用一个 visit_literal 调用（通过 | 模式）
        assert!(code.contains("Self :: Number { .. }"), "Number pattern");
        assert!(code.contains("Self :: String { .. }"), "String pattern");
        assert!(code.contains("Self :: Bool { .. }"), "Bool pattern");
        assert!(code.contains("Self :: Nil { .. }"), "Nil pattern");
    }

    // ── Ident 变体 ────────────────────────────────────────────

    #[test]
    fn ident_variant_calls_visit_ident() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Ident { name: String, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(code.contains("visit_ident (name , span)"), "Ident → visit_ident(name, span)");
    }

    // ── Fn 变体 ────────────────────────────────────────────────

    #[test]
    fn fn_variant_calls_visit_fn_with_name() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Fn { name: Option<String>, params: Vec<String>, body: Block, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(
            code.contains("visit_fn (name . as_deref () , params , body , span)"),
            "Fn → visit_fn(name.as_deref(), params, body, span)"
        );
    }

    #[test]
    fn closure_variant_calls_visit_fn_with_none() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Closure { params: Vec<String>, body: Block, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(
            code.contains("visit_fn (None , params , body , span)"),
            "Closure → visit_fn(None, params, body, span)"
        );
    }

    // ── 字段类型自动识别 ──────────────────────────────────────

    #[test]
    fn box_expr_field_recurses() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Unary { op: UnaryOp, operand: Box<Expr>, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(code.contains("visitor . visit_expr (operand)"), "Box<Expr> → visit_expr");
    }

    #[test]
    fn vec_expr_field_iterates() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Array { elements: Vec<Expr>, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(
            code.contains("for el in elements { visitor . visit_expr (el) ; }"),
            "Vec<Expr> → iterate"
        );
    }

    #[test]
    fn option_box_expr_field_conditional_recurses() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Break { value: Option<Box<Expr>>, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(
            code.contains("if let Some (v) = value { visitor . visit_expr (v) ; }"),
            "Option<Box<Expr>> → if let Some"
        );
    }

    #[test]
    fn block_field_uses_visit_block() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Loop { body: Block, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(code.contains("visitor . visit_block (body)"), "Block → visit_block");
    }

    #[test]
    fn option_block_field_conditional_recurses() {
        // 注意：变体名不能用 `Try`，因为 Try 已被特化（只访问 body）
        // 这里用 `WithKeep` 触发通用 Option<Block> 类型识别分支
        let input: DeriveInput = parse_quote! {
            enum Expr {
                WithKeep { body: Block, keep_block: Option<Block>, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(
            code.contains("if let Some (b) = keep_block { visitor . visit_block (b) ; }"),
            "Option<Block> → if let Some(b)"
        );
    }

    #[test]
    fn try_variant_only_visits_body() {
        // Try 变体特化：手写 default_visit_expr 只访问 body，忽略 keep_block/catch_clause
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Try { body: Block, catch_clause: Option<Box<CatchClause>>, keep_block: Option<Block>, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(code.contains("visitor . visit_block (body)"), "Try → visit body");
        // 不应该访问 keep_block
        assert!(
            !code.contains("keep_block"),
            "Try → must NOT visit keep_block (handwritten behavior)"
        );
        // 不应该访问 catch_clause
        assert!(
            !code.contains("catch_clause"),
            "Try → must NOT visit catch_clause (handwritten behavior)"
        );
    }

    // ── Dict 特殊处理 ─────────────────────────────────────────

    #[test]
    fn dict_variant_iterates_pairs() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Dict { pairs: Vec<(String, Expr)>, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(
            code.contains("for (_ , val) in pairs { visitor . visit_expr (val) ; }"),
            "Dict → iterate pairs, visit val"
        );
    }

    // ── Match 特殊处理 ────────────────────────────────────────

    #[test]
    fn match_variant_traverses_arms() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Match { scrutinee: Box<Expr>, arms: Vec<MatchArm>, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(code.contains("visitor . visit_expr (scrutinee)"), "Match → visit scrutinee");
        assert!(
            code.contains("MatchPattern :: Literal (lit) => visitor . visit_expr (lit)"),
            "Match arm → Literal pattern"
        );
        assert!(
            code.contains("MatchPattern :: Range { start , end , .. }"),
            "Match arm → Range pattern"
        );
        assert!(code.contains("visitor . visit_expr (& arm . body)"), "Match arm → visit body");
    }

    // ── 通用变体（多字段混合）────────────────────────────────

    #[test]
    fn binary_variant_recurses_both_operands() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Binary { left: Box<Expr>, op: BinaryOp, right: Box<Expr>, span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(code.contains("visitor . visit_expr (left)"), "Binary → visit left");
        assert!(code.contains("visitor . visit_expr (right)"), "Binary → visit right");
    }

    // ── 非枚举拒绝 ────────────────────────────────────────────

    #[test]
    fn rejects_struct() {
        let input: DeriveInput = parse_quote! {
            struct Point { x: i32, y: i32 }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_err(), "struct should be rejected");
        let err = result.unwrap_err().to_string();
        assert!(err.contains("only be derived for enums"));
    }

    // ── 单元变体 ──────────────────────────────────────────────

    #[test]
    fn unit_variant_emits_no_op() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Continue,
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        // Continue 是单元变体，不属于特殊名称 → 通用分支
        assert!(code.contains("Self :: Continue => { }"), "Continue → no-op");
    }

    // ── 方法签名 ──────────────────────────────────────────────

    #[test]
    fn generates_inherent_method() {
        let input: DeriveInput = parse_quote! {
            enum Expr {
                Nil { span: Span },
            }
        };
        let result = expand_expr_visitor(&input);
        assert!(result.is_ok());
        let code = result.unwrap().to_string();

        assert!(code.contains("impl Expr"), "generates impl block on Expr");
        assert!(
            code.contains("fn visit_children_derived < V : ExprVisitor + ? Sized >"),
            "generates visit_children_derived method with V: ExprVisitor bound"
        );
        assert!(code.contains("& self , visitor : & mut V"), "method takes &self and &mut visitor");
    }
}
