//! # nuzo_class_macros — nuzo_class 的过程宏实现
//!
//! **层级**: L0（虚拟机层 / 宿主集成层）—— 为 `nuzo_class` 提供 `#[class]`、`#[class_impl]` 等属性宏的编译期展开与校验。
//!
//! **主要入口**: [`class`], [`class_impl`], [`constructor`], [`get`], [`set`], [`method`], [`static_method`]
//!
//! 提供 `#[class]`、`#[class_impl]`、`#[constructor]`、`#[get]`、`#[set]`、`#[method]`、`#[static_method]`
//! 等属性宏，用于标记结构体与实现块，并按 Nuzo 类约定生成构造器、getter、setter、实例方法以及 serde 支持。
//!
//! `#[class]` 接受 `debug`、`default`、`clone` 参数注入常用派生；`#[class_impl]` 的 `serialize` / `deserialize`
//! 选项会收集 `#[get]` / `#[set]` 方法并生成对应的 `serde::Serialize` / `serde::Deserialize` 实现。

use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::quote;
use syn::{
    FnArg, Ident, ImplItem, ItemFn, ItemImpl, ItemStruct, Receiver, ReturnType, Signature, Type,
    parse::Parser, parse_macro_input, parse_quote, spanned::Spanned,
};

/// Marks a struct as a class and optionally injects common derives.
///
/// Recognized arguments: `debug`, `default`, `clone`.
#[proc_macro_attribute]
pub fn class(args: TokenStream, input: TokenStream) -> TokenStream {
    let args = match parse_class_args(args.into()) {
        Ok(args) => args,
        Err(err) => return err.to_compile_error().into(),
    };

    let mut item_struct = parse_macro_input!(input as ItemStruct);

    let mut derives = Vec::new();
    if args.debug {
        derives.push(quote!(Debug));
    }
    if args.default {
        derives.push(quote!(Default));
    }
    if args.clone {
        derives.push(quote!(Clone));
    }

    if !derives.is_empty() {
        let derive_attr: syn::Attribute = syn::parse_quote!(#[derive(#(#derives),*)]);
        // 将 derive 属性追加到 struct 声明之前，保留原有属性。
        item_struct.attrs.insert(0, derive_attr);
    }

    quote!(#item_struct).into()
}

#[derive(Default)]
struct ClassArgs {
    debug: bool,
    default: bool,
    clone: bool,
}

fn parse_class_args(args: proc_macro2::TokenStream) -> syn::Result<ClassArgs> {
    let mut class_args = ClassArgs::default();
    let parser = syn::meta::parser(|meta| {
        match meta.path.get_ident().map(|i| i.to_string()).as_deref() {
            Some("debug") => class_args.debug = true,
            Some("default") => class_args.default = true,
            Some("clone") => class_args.clone = true,
            _ => {
                return Err(
                    meta.error("unknown `class` argument; expected one of: debug, default, clone")
                );
            }
        }
        Ok(())
    });
    parser.parse2(args)?;
    Ok(class_args)
}

/// Marks an `impl` block for class-method processing.
///
/// Strips `#[constructor]`, `#[get]`, `#[set]`, `#[method]`, and
/// `#[static_method]` attributes from each method and validates that the
/// methods satisfy the rules of the attribute they carry.
///
/// When `serialize` is passed, a `serde::Serialize` impl is generated by
/// collecting all `#[get]` methods. When `deserialize` is passed, a
/// `serde::Deserialize` impl is generated by collecting all `#[set]` methods
/// (field names are derived from setter names by stripping the `set_` prefix).
#[proc_macro_attribute]
pub fn class_impl(args: TokenStream, input: TokenStream) -> TokenStream {
    let class_impl_args = match parse_class_impl_args(args.into()) {
        Ok(a) => a,
        Err(err) => return err.to_compile_error().into(),
    };

    let mut item_impl = parse_macro_input!(input as ItemImpl);

    // Collect serde info BEFORE process_class_impl strips the attributes.
    let getters = if class_impl_args.serialize {
        match collect_getters(&item_impl) {
            Ok(g) => g,
            Err(err) => return err.to_compile_error().into(),
        }
    } else {
        Vec::new()
    };
    let setters = if class_impl_args.deserialize {
        match collect_setters(&item_impl) {
            Ok(s) => s,
            Err(err) => return err.to_compile_error().into(),
        }
    } else {
        Vec::new()
    };
    let constructor_info =
        if class_impl_args.deserialize { collect_constructor(&item_impl) } else { None };

    if let Err(err) = process_class_impl(&mut item_impl, &class_impl_args) {
        return err.to_compile_error().into();
    }

    let mut output = quote!(#item_impl);

    if class_impl_args.serialize {
        output.extend(generate_serialize_impl_from_info(&item_impl, &getters));
    }
    if class_impl_args.deserialize {
        output.extend(generate_deserialize_impl_from_info(&item_impl, &setters, &constructor_info));
    }

    output.into()
}

#[derive(Default)]
struct ClassImplArgs {
    serialize: bool,
    deserialize: bool,
}

fn parse_class_impl_args(args: proc_macro2::TokenStream) -> syn::Result<ClassImplArgs> {
    let mut class_impl_args = ClassImplArgs::default();
    if args.is_empty() {
        return Ok(class_impl_args);
    }
    let parser = syn::meta::parser(|meta| {
        if meta.path.is_ident("serialize") {
            class_impl_args.serialize = true;
        } else if meta.path.is_ident("deserialize") {
            class_impl_args.deserialize = true;
        } else {
            return Err(meta
                .error("unknown `class_impl` argument; expected one of: serialize, deserialize"));
        }
        Ok(())
    });
    parser.parse2(args)?;
    Ok(class_impl_args)
}

fn process_class_impl(item_impl: &mut ItemImpl, _args: &ClassImplArgs) -> syn::Result<()> {
    let mut combined_err: Option<syn::Error> = None;

    for item in &mut item_impl.items {
        if let ImplItem::Fn(method) = item {
            match extract_class_attr(&mut method.attrs) {
                Ok(Some(kind)) => {
                    if let Err(err) = validate_method_kind(kind, &method.sig) {
                        combine_error(&mut combined_err, err);
                    }
                }
                Ok(None) => {}
                Err(err) => combine_error(&mut combined_err, err),
            }
        }
    }

    match combined_err {
        Some(err) => Err(err),
        None => Ok(()),
    }
}

fn combine_error(acc: &mut Option<syn::Error>, err: syn::Error) {
    if let Some(acc_err) = acc {
        acc_err.combine(err);
    } else {
        *acc = Some(err);
    }
}

/// Marks a method as a constructor.
///
/// The return type must be `Self`.
#[proc_macro_attribute]
pub fn constructor(_args: TokenStream, input: TokenStream) -> TokenStream {
    let item_fn = parse_macro_input!(input as ItemFn);
    if let Err(err) = validate_constructor(&item_fn.sig) {
        return err.to_compile_error().into();
    }
    quote!(#item_fn).into()
}

/// Marks a method as a getter.
///
/// The first argument must be `&self` and the return type must not be `()`.
#[proc_macro_attribute]
pub fn get(_args: TokenStream, input: TokenStream) -> TokenStream {
    let item_fn = parse_macro_input!(input as ItemFn);
    if let Err(err) = validate_getter(&item_fn.sig) {
        return err.to_compile_error().into();
    }
    quote!(#item_fn).into()
}

/// Marks a method as a setter.
///
/// The first argument must be `&mut self` and the return type must be `()`.
#[proc_macro_attribute]
pub fn set(_args: TokenStream, input: TokenStream) -> TokenStream {
    let item_fn = parse_macro_input!(input as ItemFn);
    if let Err(err) = validate_setter(&item_fn.sig) {
        return err.to_compile_error().into();
    }
    quote!(#item_fn).into()
}

/// Marks a method as an instance method.
///
/// The first argument must be `&self` or `&mut self`.
#[proc_macro_attribute]
pub fn method(_args: TokenStream, input: TokenStream) -> TokenStream {
    let item_fn = parse_macro_input!(input as ItemFn);
    if let Err(err) = validate_method(&item_fn.sig) {
        return err.to_compile_error().into();
    }
    quote!(#item_fn).into()
}

/// Marks a method as a static method.
///
/// The method must not take `self`.
#[proc_macro_attribute]
pub fn static_method(_args: TokenStream, input: TokenStream) -> TokenStream {
    let item_fn = parse_macro_input!(input as ItemFn);
    if let Err(err) = validate_static_method(&item_fn.sig) {
        return err.to_compile_error().into();
    }
    quote!(#item_fn).into()
}

#[derive(Clone, Copy, PartialEq)]
enum MethodKind {
    Constructor,
    Get,
    Set,
    Method,
    StaticMethod,
}

fn method_kind_name(kind: MethodKind) -> &'static str {
    match kind {
        MethodKind::Constructor => "constructor",
        MethodKind::Get => "get",
        MethodKind::Set => "set",
        MethodKind::Method => "method",
        MethodKind::StaticMethod => "static_method",
    }
}

fn method_kind_from_path(path: &syn::Path) -> Option<MethodKind> {
    match path.get_ident()?.to_string().as_str() {
        "constructor" => Some(MethodKind::Constructor),
        "get" => Some(MethodKind::Get),
        "set" => Some(MethodKind::Set),
        "method" => Some(MethodKind::Method),
        "static_method" => Some(MethodKind::StaticMethod),
        _ => None,
    }
}

fn extract_class_attr(attrs: &mut Vec<syn::Attribute>) -> syn::Result<Option<MethodKind>> {
    let mut found: Option<(MethodKind, Span)> = None;
    let mut retained = Vec::with_capacity(attrs.len());

    for attr in attrs.drain(..) {
        if let Some(kind) = method_kind_from_path(attr.path()) {
            let span = attr.span();
            if let Some((prev_kind, prev_span)) = found {
                let mut err = syn::Error::new(
                    span,
                    format!(
                        "multiple class attributes on the same method: `#[{}]` conflicts with `#[{}]`",
                        method_kind_name(kind),
                        method_kind_name(prev_kind)
                    ),
                );
                err.combine(syn::Error::new(prev_span, "previous class attribute here"));
                return Err(err);
            }
            found = Some((kind, span));
        } else {
            retained.push(attr);
        }
    }

    *attrs = retained;
    Ok(found.map(|(k, _)| k))
}

fn validate_method_kind(kind: MethodKind, sig: &Signature) -> syn::Result<()> {
    match kind {
        MethodKind::Constructor => validate_constructor(sig),
        MethodKind::Get => validate_getter(sig),
        MethodKind::Set => validate_setter(sig),
        MethodKind::Method => validate_method(sig),
        MethodKind::StaticMethod => validate_static_method(sig),
    }
}

fn validate_constructor(sig: &Signature) -> syn::Result<()> {
    match &sig.output {
        ReturnType::Default => {
            Err(syn::Error::new_spanned(&sig.output, "#[constructor] must return `Self`"))
        }
        ReturnType::Type(_, ty) => {
            if is_self_type(ty) {
                Ok(())
            } else {
                Err(syn::Error::new_spanned(ty, "#[constructor] must return `Self`"))
            }
        }
    }
}

fn validate_getter(sig: &Signature) -> syn::Result<()> {
    let receiver = first_receiver(sig).ok_or_else(|| {
        syn::Error::new_spanned(sig, "#[get] method must take `&self` as the first argument")
    })?;

    if receiver.reference.is_none() || receiver.mutability.is_some() {
        return Err(syn::Error::new_spanned(
            receiver,
            "#[get] method first argument must be `&self`",
        ));
    }

    match &sig.output {
        ReturnType::Default => {
            Err(syn::Error::new_spanned(&sig.output, "#[get] method must not return `()`"))
        }
        ReturnType::Type(_, ty) => {
            if is_unit_type(ty) {
                Err(syn::Error::new_spanned(ty, "#[get] method must not return `()`"))
            } else {
                Ok(())
            }
        }
    }
}

fn validate_setter(sig: &Signature) -> syn::Result<()> {
    let receiver = first_receiver(sig).ok_or_else(|| {
        syn::Error::new_spanned(sig, "#[set] method must take `&mut self` as the first argument")
    })?;

    if receiver.reference.is_none() || receiver.mutability.is_none() {
        return Err(syn::Error::new_spanned(
            receiver,
            "#[set] method first argument must be `&mut self`",
        ));
    }

    match &sig.output {
        ReturnType::Default => Ok(()),
        ReturnType::Type(_, ty) => {
            if is_unit_type(ty) {
                Ok(())
            } else {
                Err(syn::Error::new_spanned(ty, "#[set] method must return `()`"))
            }
        }
    }
}

fn validate_method(sig: &Signature) -> syn::Result<()> {
    let receiver = first_receiver(sig).ok_or_else(|| {
        syn::Error::new_spanned(
            sig,
            "#[method] method must take `&self` or `&mut self` as the first argument",
        )
    })?;

    if receiver.reference.is_none() {
        return Err(syn::Error::new_spanned(
            receiver,
            "#[method] method first argument must be `&self` or `&mut self`",
        ));
    }

    Ok(())
}

fn validate_static_method(sig: &Signature) -> syn::Result<()> {
    for input in &sig.inputs {
        if let FnArg::Receiver(receiver) = input {
            return Err(syn::Error::new_spanned(receiver, "#[static_method] must not take `self`"));
        }
    }
    Ok(())
}

fn first_receiver(sig: &Signature) -> Option<&Receiver> {
    match sig.inputs.first()? {
        FnArg::Receiver(receiver) => Some(receiver),
        FnArg::Typed(_) => None,
    }
}

fn is_self_type(ty: &Type) -> bool {
    match ty {
        Type::Path(type_path) => type_path.path.is_ident("Self"),
        _ => false,
    }
}

fn is_unit_type(ty: &Type) -> bool {
    match ty {
        Type::Tuple(tuple) => tuple.elems.is_empty(),
        _ => false,
    }
}

/// Collected info about a `#[get]` method for Serialize generation.
struct GetterInfo {
    /// The method name (used to invoke the getter).
    name: Ident,
    /// The serialized field key (from `#[get(rename = "...")]` or method name).
    serialized_name: String,
    /// The return type of the getter.
    return_type: Type,
    /// Whether this getter should be skipped during serialization.
    skip: bool,
}

/// Collected info about a `#[set]` method for Deserialize generation.
struct SetterInfo {
    /// The setter method name (e.g. `set_age`).
    method_name: Ident,
    /// The derived internal field name (e.g. `age` from `set_age`).
    field_name: String,
    /// The serialized field key (from `#[set(rename_from = "...")]` or `field_name`).
    serialized_name: String,
    /// The parameter type of the setter.
    param_type: Type,
}

/// Parse `#[get(...)]` arguments.
///
/// Returns `(serialized_name, skip)`.
/// - `#[get]` or `#[get(rename)]` without value is an error for `rename`.
/// - `#[get(skip)]` sets `skip = true`.
/// - `#[get(skip = true)]` is rejected because `skip` takes no value.
fn parse_getter_args(attrs: &[syn::Attribute], method_name: &Ident) -> syn::Result<(String, bool)> {
    let mut serialized_name = method_name.to_string();
    let mut skip = false;

    for attr in attrs {
        if attr.path().is_ident("get") {
            if matches!(attr.meta, syn::Meta::Path(_)) {
                continue;
            }
            attr.parse_args_with(syn::meta::parser(|meta| {
                if meta.path.is_ident("rename") {
                    let value = meta.value()?;
                    let lit: syn::LitStr = value.parse()?;
                    serialized_name = lit.value();
                } else if meta.path.is_ident("skip") {
                    if meta.input.peek(syn::Token![=]) {
                        return Err(meta.error("`skip` does not take a value"));
                    }
                    skip = true;
                } else {
                    return Err(
                        meta.error("unknown `get` argument; expected `rename = \"...\"` or `skip`")
                    );
                }
                Ok(())
            }))?;
        }
    }

    Ok((serialized_name, skip))
}

/// Parse `#[set(...)]` arguments.
///
/// Returns the serialized field name. `#[set]` defaults to the derived `field_name`;
/// `#[set(rename_from = "...")]` overrides it.
fn parse_setter_args(attrs: &[syn::Attribute], field_name: &str) -> syn::Result<String> {
    let mut serialized_name = field_name.to_string();

    for attr in attrs {
        if attr.path().is_ident("set") {
            if matches!(attr.meta, syn::Meta::Path(_)) {
                continue;
            }
            attr.parse_args_with(syn::meta::parser(|meta| {
                if meta.path.is_ident("rename_from") {
                    let value = meta.value()?;
                    let lit: syn::LitStr = value.parse()?;
                    serialized_name = lit.value();
                } else {
                    return Err(
                        meta.error("unknown `set` argument; expected `rename_from = \"...\"`")
                    );
                }
                Ok(())
            }))?;
        }
    }

    Ok(serialized_name)
}

fn collect_getters(item_impl: &ItemImpl) -> syn::Result<Vec<GetterInfo>> {
    let mut getters = Vec::new();
    for item in &item_impl.items {
        if let ImplItem::Fn(method) = item
            && has_class_attr(&method.attrs, MethodKind::Get)
        {
            let name = method.sig.ident.clone();
            let (serialized_name, skip) = parse_getter_args(&method.attrs, &name)?;
            let return_type = match &method.sig.output {
                ReturnType::Type(_, ty) => (*ty).clone(),
                ReturnType::Default => continue, // validated earlier: getters must return
            };
            getters.push(GetterInfo { name, serialized_name, return_type: *return_type, skip });
        }
    }
    Ok(getters)
}

fn collect_setters(item_impl: &ItemImpl) -> syn::Result<Vec<SetterInfo>> {
    let mut setters = Vec::new();
    for item in &item_impl.items {
        if let ImplItem::Fn(method) = item
            && has_class_attr(&method.attrs, MethodKind::Set)
        {
            let method_name = method.sig.ident.clone();
            let field_name = derive_field_name_from_setter(&method_name.to_string());
            let serialized_name = parse_setter_args(&method.attrs, &field_name)?;
            let param_type = match method.sig.inputs.iter().nth(1) {
                Some(FnArg::Typed(pat_type)) => (*pat_type.ty).clone(),
                _ => continue, // validated earlier: setters must have &mut self + value
            };
            setters.push(SetterInfo { method_name, field_name, serialized_name, param_type });
        }
    }
    Ok(setters)
}

/// Derive a field name from a setter method name.
///
/// - `set_age` → `age`
/// - `set_name` → `name`
/// - `set_value` → `value`
/// - If no `set_` prefix, use the method name as-is.
fn derive_field_name_from_setter(method_name: &str) -> String {
    if let Some(stripped) = method_name.strip_prefix("set_") {
        stripped.to_string()
    } else {
        method_name.to_string()
    }
}

/// Check if the method has a specific class attribute (without removing it).
fn has_class_attr(attrs: &[syn::Attribute], kind: MethodKind) -> bool {
    attrs.iter().any(|attr| method_kind_from_path(attr.path()) == Some(kind))
}

/// Extract the self type from an impl block.
///
/// For `impl Foo { ... }` returns `Foo`.
/// For `impl<T> Wrapper<T> { ... }` returns `Wrapper<T>`.
fn impl_self_type(item_impl: &ItemImpl) -> Type {
    (*item_impl.self_ty).clone()
}

/// Extract the generic parameters and where clause from an impl block.
///
/// Returns `(impl_generics, type_generics, where_clause)` suitable for
/// `quote! { impl #impl_generics ... for #ty #type_generics #where_clause { ... } }`.
fn impl_generics_split(
    item_impl: &ItemImpl,
) -> (proc_macro2::TokenStream, proc_macro2::TokenStream, Option<&syn::WhereClause>) {
    let (impl_generics, type_generics, where_clause) = item_impl.generics.split_for_impl();
    (quote!(#impl_generics), quote!(#type_generics), where_clause)
}

/// Add a bound to every type parameter in a set of generics.
fn add_serde_bounds(
    generics: &syn::Generics,
    bound_fn: impl Fn(&syn::TypeParam) -> syn::TypeParamBound,
) -> syn::Generics {
    let mut generics = generics.clone();
    for param in &mut generics.params {
        if let syn::GenericParam::Type(type_param) = param {
            let bound = bound_fn(type_param);
            type_param.bounds.push(bound);
        }
    }
    generics
}

/// Generate a `serde::Serialize` impl by calling each `#[get]` method.
///
/// For example, given:
/// ```ignore
/// #[class_impl(serialize)]
/// impl Person {
///     #[get] fn name(&self) -> &str { &self.name }
///     #[get] fn age(&self) -> u32 { self.age }
/// }
/// ```
///
/// Generates:
/// ```ignore
/// impl serde::Serialize for Person {
///     fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
///         use serde::ser::SerializeStruct;
///         let mut s = serializer.serialize_struct("Person", 2)?;
///         s.serialize_field("name", self.name())?;
///         s.serialize_field("age", &self.age())?;
///         s.end()
///     }
/// }
/// ```
fn generate_serialize_impl_from_info(
    item_impl: &ItemImpl,
    getters: &[GetterInfo],
) -> proc_macro2::TokenStream {
    let active_getters: Vec<&GetterInfo> = getters.iter().filter(|g| !g.skip).collect();
    if active_getters.is_empty() {
        return quote! {
            compile_error!("#[class_impl(serialize)] requires at least one non-skipped #[get] method");
        };
    }

    let ty = impl_self_type(item_impl);
    let generics = add_serde_bounds(&item_impl.generics, |_| parse_quote!(serde::Serialize));
    let (impl_generics, type_generics, where_clause) = generics.split_for_impl();
    let impl_generics = quote!(#impl_generics);
    let _type_generics = quote!(#type_generics);

    let type_name = quote!(#ty).to_string().replace(' ', "");
    let field_count = active_getters.len();

    let serialize_fields: Vec<proc_macro2::TokenStream> = active_getters
        .iter()
        .map(|getter| {
            let name_str = &getter.serialized_name;
            let method_name = &getter.name;
            let return_type = &getter.return_type;

            // If the getter returns a reference (&T), we can pass it directly.
            // If it returns a value (T), we need to take a reference.
            match return_type {
                Type::Reference(_) => quote! {
                    __s.serialize_field(#name_str, self.#method_name())?;
                },
                _ => quote! {
                    __s.serialize_field(#name_str, &self.#method_name())?;
                },
            }
        })
        .collect();

    quote! {
        impl #impl_generics serde::Serialize for #ty #where_clause {
            fn serialize<__S>(&self, __serializer: __S) -> ::std::result::Result<__S::Ok, __S::Error>
            where
                __S: serde::Serializer,
            {
                use serde::ser::SerializeStruct;
                let mut __s = __serializer.serialize_struct(#type_name, #field_count)?;
                #(#serialize_fields)*
                __s.end()
            }
        }
    }
}

/// Collect constructor params and setter fields, deduplicating by `field_name`.
///
/// Returns `(serialized_name, field_name, type)` tuples. When a constructor param
/// and a setter share the same `field_name`, the setter's `serialized_name`
/// (e.g. from `rename_from`) takes priority over the constructor param name.
fn collect_and_dedup_fields(
    constructor: &Option<ConstructorInfo>,
    setters: &[SetterInfo],
) -> Vec<(String, String, Type)> {
    let mut field_map: std::collections::HashMap<String, (String, Type)> =
        std::collections::HashMap::new();

    if let Some(ctor) = constructor {
        for (name, ty) in &ctor.params {
            field_map.entry(name.clone()).or_insert((name.clone(), (*ty).clone()));
        }
    }

    // Then, process setters. If a setter's field_name matches a constructor param,
    // update the serialized_name from the setter (rename_from takes priority).
    // Otherwise, add as a new field.
    for setter in setters {
        match field_map.entry(setter.field_name.clone()) {
            std::collections::hash_map::Entry::Occupied(mut entry) => {
                // Setter's serialized_name (e.g. from rename_from) takes priority.
                entry.get_mut().0 = setter.serialized_name.clone();
            }
            std::collections::hash_map::Entry::Vacant(entry) => {
                entry.insert((setter.serialized_name.clone(), setter.param_type.clone()));
            }
        }
    }

    field_map
        .into_iter()
        .map(|(field_name, (serialized_name, ty))| (serialized_name, field_name, ty))
        .collect()
}

/// Generate the `__Field` enum used to match deserialized field names.
fn generate_field_enum(field_names: &[Ident]) -> proc_macro2::TokenStream {
    quote! {
        enum __Field {
            #(#field_names,)*
            __Ignore,
        }
    }
}

/// Generate the `serde::Deserialize` implementation and visitor for `__Field`.
fn generate_field_visitor(
    field_names_str: &[String],
    field_idents: &[Ident],
    de_lifetime: &syn::Lifetime,
) -> proc_macro2::TokenStream {
    let de_lifetime_decl = quote!(#de_lifetime);
    let de_lifetime_use = quote!(#de_lifetime);

    quote! {
        impl<#de_lifetime_decl> serde::Deserialize<#de_lifetime_use> for __Field {
            fn deserialize<__D>(__deserializer: __D) -> ::std::result::Result<Self, __D::Error>
            where
                __D: serde::Deserializer<#de_lifetime_use>,
            {
                struct __FieldVisitorInner;

                impl<#de_lifetime_decl> Visitor<#de_lifetime_use> for __FieldVisitorInner {
                    type Value = __Field;

                    fn expecting(&self, __formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                        write!(__formatter, "field name")
                    }

                    fn visit_str<__E>(self, __value: &str) -> ::std::result::Result<__Field, __E>
                    where
                        __E: serde::de::Error,
                    {
                        match __value {
                            #(#field_names_str => ::std::result::Result::Ok(__Field::#field_idents),)*
                            _ => ::std::result::Result::Ok(__Field::__Ignore),
                        }
                    }
                }

                __deserializer.deserialize_identifier(__FieldVisitorInner)
            }
        }
    }
}

/// Generate the `__StructVisitor` struct definition and its initializer.
///
/// Returns `(visitor_struct_def, visitor_init)`.
fn generate_struct_visitor(
    item_impl: &ItemImpl,
    de_lifetime: &syn::Lifetime,
    is_generic: bool,
) -> (proc_macro2::TokenStream, proc_macro2::TokenStream) {
    let _de_lifetime = de_lifetime;
    let ty = impl_self_type(item_impl);
    let (impl_generics, _type_generics, where_clause) = impl_generics_split(item_impl);

    if is_generic {
        (
            quote! {
                struct __StructVisitor #impl_generics #where_clause {
                    _phantom: ::std::marker::PhantomData<fn() -> #ty>,
                }
            },
            quote! {
                __StructVisitor {
                    _phantom: ::std::marker::PhantomData,
                }
            },
        )
    } else {
        (
            quote! {
                struct __StructVisitor;
            },
            quote! {
                __StructVisitor
            },
        )
    }
}

/// Generate the body of the `visit_map` method.
///
/// This includes the local `Option<T>` variables, the field-reading loop,
/// and the final construction code.
fn generate_visit_map_body(
    all_fields: &[(String, String, Type)],
    constructor: &Option<ConstructorInfo>,
    setters: &[SetterInfo],
    field_idents: &[Ident],
    ty: &Type,
) -> proc_macro2::TokenStream {
    let construct_code = generate_construct_code(ty, constructor, setters, all_fields);

    let let_typed_fields: Vec<proc_macro2::TokenStream> = all_fields
        .iter()
        .map(|(_, field_name, ty)| {
            let var_ident = Ident::new(&format!("__{}", field_name), Span::call_site());
            quote! { let mut #var_ident: ::std::option::Option<#ty> = None; }
        })
        .collect();

    let visit_map_arms_typed: Vec<proc_macro2::TokenStream> = all_fields
        .iter()
        .zip(field_idents.iter())
        .map(|((serialized_name, field_name, _), field_ident)| {
            let var_ident = Ident::new(&format!("__{}", field_name), Span::call_site());
            quote! {
                __Field::#field_ident => {
                    if #var_ident.is_some() {
                        return Err(<__A::Error as serde::de::Error>::duplicate_field(#serialized_name));
                    }
                    #var_ident = ::std::option::Option::Some(__map.next_value()?);
                }
            }
        })
        .collect();

    quote! {
        #(#let_typed_fields)*

        while let ::std::option::Option::Some(__key) = __map.next_key::<__Field>()? {
            match __key {
                #(#visit_map_arms_typed)*
                __Field::__Ignore => {
                    let _ = __map.next_value::<serde::de::IgnoredAny>()?;
                }
            }
        }

        #construct_code
    }
}

/// Generate a `serde::Deserialize` impl by calling each `#[set]` method.
///
/// For example, given:
/// ```ignore
/// #[class_impl(deserialize)]
/// impl Person {
///     #[constructor] fn new(name: String, age: u32) -> Self { Self { name, age } }
///     #[set] fn set_age(&mut self, age: u32) { self.age = age; }
/// }
/// ```
///
/// Generates a visitor that deserializes fields and constructs via `new()`
/// for constructor parameters, then applies setters for the remaining fields.
fn generate_deserialize_impl_from_info(
    item_impl: &ItemImpl,
    setters: &[SetterInfo],
    constructor: &Option<ConstructorInfo>,
) -> proc_macro2::TokenStream {
    if constructor.is_none() && setters.is_empty() {
        return quote! {
            compile_error!("#[class_impl(deserialize)] requires at least one #[constructor] or #[set] method");
        };
    }

    let ty = impl_self_type(item_impl);

    let de_lifetime = syn::Lifetime::new("'__nuzo_de", proc_macro2::Span::call_site());
    let de_lifetime_use = quote!(#de_lifetime);

    // For Deserialize, inject lifetime + bounds into a copy of the generics.
    // We build the where-clause bounds inline via quote! to guarantee token
    // identity between the lifetime param and its usage in trait bounds.
    let mut serde_generics = item_impl.generics.clone();
    serde_generics
        .params
        .insert(0, syn::GenericParam::Lifetime(syn::LifetimeParam::new(de_lifetime.clone())));
    let (impl_generics, _serde_type_generics, base_where_clause) = serde_generics.split_for_impl();

    let serde_where_bounds: Vec<proc_macro2::TokenStream> = item_impl
        .generics
        .params
        .iter()
        .filter_map(|p| match p {
            syn::GenericParam::Type(tp) => {
                let ident = &tp.ident;
                Some(quote!(#ident: serde::Deserialize<#de_lifetime_use>))
            }
            _ => None,
        })
        .collect();

    let where_clause = if serde_where_bounds.is_empty() || base_where_clause.is_none() {
        quote!(where #(#serde_where_bounds),*)
    } else {
        quote!(#base_where_clause, #(#serde_where_bounds),*)
    };

    let mut visitor_generics = item_impl.generics.clone();
    visitor_generics
        .params
        .insert(0, syn::GenericParam::Lifetime(syn::LifetimeParam::new(de_lifetime.clone())));
    let (_visitor_impl_generics, _visitor_type_generics, _visitor_where_clause) =
        visitor_generics.split_for_impl();

    let type_name = quote!(#ty).to_string().replace(' ', "");

    let all_fields = collect_and_dedup_fields(constructor, setters);
    if all_fields.is_empty() {
        return quote! {
            compile_error!("#[class_impl(deserialize)] found no fields to deserialize");
        };
    }

    let field_names_str: Vec<String> =
        all_fields.iter().map(|(serialized_name, _, _)| serialized_name.clone()).collect();
    let field_idents: Vec<Ident> = all_fields
        .iter()
        .map(|(_, field_name, _)| Ident::new(field_name, Span::call_site()))
        .collect();

    let field_enum = generate_field_enum(&field_idents);
    let field_visitor = generate_field_visitor(&field_names_str, &field_idents, &de_lifetime);

    let is_generic = !item_impl.generics.params.is_empty();
    let (visitor_struct_def, visitor_init) =
        generate_struct_visitor(item_impl, &de_lifetime, is_generic);

    // Original type generics (without injected lifetime) for `for __StructVisitor` target.
    let (_orig_impl_generics, orig_type_generics, _orig_where_clause) =
        impl_generics_split(item_impl);

    // Visitor impl needs its own where clause with Deserialize bounds,
    // because next_value() calls inside visit_map require them and
    // the outer Deserialize impl's where clause doesn't propagate inward.
    let visitor_where_clause = if serde_where_bounds.is_empty() {
        quote!()
    } else {
        quote!(where #(#serde_where_bounds),*)
    };

    let visit_map_body =
        generate_visit_map_body(&all_fields, constructor, setters, &field_idents, &ty);

    quote! {
        impl #impl_generics serde::Deserialize<#de_lifetime_use> for #ty #where_clause {
            fn deserialize<__D>(__deserializer: __D) -> ::std::result::Result<Self, __D::Error>
            where
                __D: serde::Deserializer<#de_lifetime_use>,
            {
                use serde::de::{MapAccess, Visitor};
                use std::fmt;

                #field_enum

                #field_visitor

                #visitor_struct_def

                impl #_visitor_impl_generics Visitor<#de_lifetime_use> for __StructVisitor #orig_type_generics #visitor_where_clause {
                    type Value = #ty;

                    fn expecting(&self, __formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                        write!(__formatter, "struct {}", #type_name)
                    }

                    fn visit_map<__A>(self, mut __map: __A) -> ::std::result::Result<Self::Value, __A::Error>
                    where
                        __A: MapAccess<#de_lifetime_use>,
                    {
                        #visit_map_body
                    }
                }

                __deserializer.deserialize_struct(
                    #type_name,
                    &[#(#field_names_str),*],
                    #visitor_init,
                )
            }
        }
    }
}

/// Collected info about a `#[constructor]` method for Deserialize generation.
struct ConstructorInfo {
    /// Parameter names and types (excluding `self`).
    params: Vec<(String, Type)>,
}

fn collect_constructor(item_impl: &ItemImpl) -> Option<ConstructorInfo> {
    for item in &item_impl.items {
        if let ImplItem::Fn(method) = item
            && has_class_attr(&method.attrs, MethodKind::Constructor)
        {
            let params: Vec<(String, Type)> = method
                .sig
                .inputs
                .iter()
                .filter_map(|arg| {
                    if let FnArg::Typed(pat_type) = arg {
                        let name = match &*pat_type.pat {
                            syn::Pat::Ident(pat_ident) => pat_ident.ident.to_string(),
                            _ => return None,
                        };
                        Some((name, (*pat_type.ty).clone()))
                    } else {
                        None
                    }
                })
                .collect();
            return Some(ConstructorInfo { params });
        }
    }
    None
}

/// Generate the construction code for Deserialize.
///
/// Strategy:
/// 1. If a constructor exists, extract required constructor params from the
///    deserialized result, call `<Ty>::new(...)`, then apply setters.
/// 2. If no constructor, require Default + apply setters.
fn generate_construct_code(
    ty: &Type,
    constructor: &Option<ConstructorInfo>,
    setters: &[SetterInfo],
    _all_fields: &[(String, String, Type)],
) -> proc_macro2::TokenStream {
    let ctor_param_names: std::collections::HashSet<String> = match constructor {
        Some(ctor) => ctor.params.iter().map(|(n, _)| n.clone()).collect(),
        None => std::collections::HashSet::new(),
    };

    match constructor {
        Some(ctor) => {
            let _ctor_param_idents: Vec<Ident> = ctor
                .params
                .iter()
                .map(|(n, _)| Ident::new(&format!("__{}", n), Span::call_site()))
                .collect();

            let ctor_missing_checks: Vec<proc_macro2::TokenStream> = ctor
                .params
                .iter()
                .map(|(name, _)| {
                    let var_ident = Ident::new(&format!("__{}", name), Span::call_site());
                    quote! {
                        let #var_ident = #var_ident.ok_or_else(|| {
                            <__A::Error as serde::de::Error>::missing_field(#name)
                        })?;
                    }
                })
                .collect();

            // Generate setter calls. Only apply setters whose field name is NOT
            // already a constructor param (to avoid double-setting).
            let setter_calls: Vec<proc_macro2::TokenStream> = setters
                .iter()
                .filter(|setter| !ctor_param_names.contains(&setter.field_name))
                .map(|setter| {
                    let method_name = &setter.method_name;
                    let var_ident =
                        Ident::new(&format!("__{}", setter.field_name), Span::call_site());
                    quote! {
                        if let ::std::option::Option::Some(__val) = #var_ident {
                            __instance.#method_name(__val);
                        }
                    }
                })
                .collect();

            // 重要修复：必须使用 __ 前缀的变量名，因为那是我们在 visit_map 中声明的局部变量
            let ctor_call_idents: Vec<Ident> = ctor
                .params
                .iter()
                .map(|(n, _)| Ident::new(&format!("__{}", n), Span::call_site()))
                .collect();

            quote! {
                #(#ctor_missing_checks)*
                // 重要修复：使用完整类型名 #ty 而不是 Self
                // 因为在 visit_map 作用域中，Self 指的是 __StructVisitor 而不是目标类型
                let mut __instance = <#ty>::new(#(#ctor_call_idents),*);
                #(#setter_calls)*
                ::std::result::Result::Ok(__instance)
            }
        }
        None => {
            // No constructor: require Default, apply setters.
            let setter_calls: Vec<proc_macro2::TokenStream> = setters
                .iter()
                .map(|setter| {
                    let method_name = &setter.method_name;
                    let var_ident =
                        Ident::new(&format!("__{}", setter.field_name), Span::call_site());
                    quote! {
                        if let ::std::option::Option::Some(__val) = #var_ident {
                            __instance.#method_name(__val);
                        }
                    }
                })
                .collect();

            quote! {
                // 重要修复：使用完整类型名 #ty 而不是 Self
                let mut __instance = <#ty as ::std::default::Default>::default();
                #(#setter_calls)*
                ::std::result::Result::Ok(__instance)
            }
        }
    }
}
